### ISSUE TITLE
Topic being recreated after deletion

### ISSUE THREAD

**Issue by conorfennell** [danielqsj/kafka_exporter#45]
Version: `danielqsj/kafka-exporter:v1.1.0`

## Observation 

I have a hunch that there is a race condition when:
Step 1. `kafka-exporter` -> Request for current topics  
Step 2. Someone deletes a topic
Step 3. `kafka-exporter` -> Request for deleted topic metadata which cause the topic to be recreated with default parmameters.

## Reproduce

While kafka exporter is running.

Step 1: Create Topic
```kafka-topics --zookeeper $ZOOKEEPER --create --topic delete-me --partitions 3 --replication-factor 1```

Step 2: Delete Topic
```kafka-topics --zookeeper $ZOOKEEPER --delete --topic delete-me```

Step 3: List topics; wait 0-30 seconds
```kafka-topics --zookeeper $ZOOKEEPER --list```

**Comment by danielqsj** [comment]
@conorfennell This is fixed in v1.2.0. Please try the newest image.

**Comment by conorfennell** [comment]
@danielqsj 
Thank you! just verified it.

**Comment by canghai118** [comment]
我最近也遇到这个问题。能指出具体哪个commit中修复的这个问题吗？ 学习一下是如何修复的。 thanks

> @conorfennell This is fixed in v1.2.0. Please try the newest image.

**Comment by canghai118** [comment]
I think this bug still exists in latest version, currenty is v1.3.1

kafka cluster is configured with `auto.topic.create.enabled = true`,  topic is recreated by kafka-exporter after delete

**Comment by canghai118** [comment]
I think update to latest sarama may solve this problem

AllowAutoTopicCreation now can be disabled through client configration.

https://github.com/Shopify/sarama/blob/master/client.go#L879

**Comment by menghe999** [comment]
> 我最近也遇到这个问题。能指出具体哪个commit中修复的这个问题吗？ 学习一下是如何修复的。 thanks
> 
> > @conorfennell This is fixed in v1.2.0. Please try the newest image.

+1
